import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AuthProvider from './providers/AuthProvider';
import AxiosInterceptorProvider from './providers/AxiosInterceptorProvider';
import MswProvider from './providers/MswProvider';
import QueryProvider from './providers/QueryProvider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MswProvider>
          <QueryProvider>
            <AxiosInterceptorProvider>
              <AuthProvider>{children}</AuthProvider>
            </AxiosInterceptorProvider>
          </QueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
