import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AuthProvider from './providers/AuthProvider';
import InterceptorProvider from './providers/interceptor/InterceptorProvider';
import MswProvider from './providers/MswProvider';
import QueryProvider from './providers/QueryProvider';

import './styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <MswProvider>
        <QueryProvider>
          <InterceptorProvider>
            <AuthProvider>{children}</AuthProvider>
          </InterceptorProvider>
        </QueryProvider>
      </MswProvider>
    </body>
  </html>
);

export default RootLayout;
